-- MySQL Script generated by MySQL Workbench
-- Tue Mar 12 12:58:01 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema OdisityLocal
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema OdisityLocal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `OdisityLocal` DEFAULT CHARACTER SET utf8 ;
USE `OdisityLocal` ;

-- -----------------------------------------------------
-- Table `OdisityLocal`.`Miners`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OdisityLocal`.`Miners` ;

CREATE TABLE IF NOT EXISTS `OdisityLocal`.`Miners` (
  `idMiners` INT NOT NULL,
  `MinerName` VARCHAR(45) NULL,
  `WorkerName` VARCHAR(45) NULL,
  PRIMARY KEY (`idMiners`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OdisityLocal`.`Currency`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OdisityLocal`.`Currency` ;

CREATE TABLE IF NOT EXISTS `OdisityLocal`.`Currency` (
  `idCurrency` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `FullName` VARCHAR(45) NULL,
  `Wallet` VARCHAR(45) NULL,
  `idMiners` INT NOT NULL,
  PRIMARY KEY (`idCurrency`, `idMiners`),
  INDEX `fk_Currency_Miners1_idx` (`idMiners` ASC),
  CONSTRAINT `fk_Currency_Miners1`
    FOREIGN KEY (`idMiners`)
    REFERENCES `OdisityLocal`.`Miners` (`idMiners`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OdisityLocal`.`Pools`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OdisityLocal`.`Pools` ;

CREATE TABLE IF NOT EXISTS `OdisityLocal`.`Pools` (
  `idPools` INT NOT NULL AUTO_INCREMENT,
  `PoolName` VARCHAR(45) NULL,
  `Ports` VARCHAR(45) NULL,
  `idCurrency` INT NOT NULL,
  PRIMARY KEY (`idPools`),
  INDEX `fk_Pools_Currency1_idx` (`idCurrency` ASC),
  CONSTRAINT `fk_Pools_Currency1`
    FOREIGN KEY (`idCurrency`)
    REFERENCES `OdisityLocal`.`Currency` (`idCurrency`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OdisityLocal`.`Regions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OdisityLocal`.`Regions` ;

CREATE TABLE IF NOT EXISTS `OdisityLocal`.`Regions` (
  `idRegions` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Location` VARCHAR(45) NULL,
  PRIMARY KEY (`idRegions`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OdisityLocal`.`Pools_has_Regions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `OdisityLocal`.`Pools_has_Regions` ;

CREATE TABLE IF NOT EXISTS `OdisityLocal`.`Pools_has_Regions` (
  `idPools` INT NOT NULL,
  `idRegions` INT NOT NULL,
  `Server` VARCHAR(45) NULL,
  PRIMARY KEY (`idPools`, `idRegions`),
  INDEX `fk_Pools_has_Regions_Regions1_idx` (`idRegions` ASC),
  INDEX `fk_Pools_has_Regions_Pools_idx` (`idPools` ASC),
  CONSTRAINT `fk_Pools_has_Regions_Pools`
    FOREIGN KEY (`idPools`)
    REFERENCES `OdisityLocal`.`Pools` (`idPools`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pools_has_Regions_Regions1`
    FOREIGN KEY (`idRegions`)
    REFERENCES `OdisityLocal`.`Regions` (`idRegions`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
